---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-service
  namespace: elk-new
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
    - port: 9200
      name: es-9200
      protocol: TCP
      targetPort: 9200
    - port: 9300
      protocol: TCP
      name: es-9300
      targetPort: 9300
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: elk-new
spec:
  serviceName: elasticsearch-service
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.11.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: 5600Mi
            requests:
              cpu: "2"
              memory: 2048Mi
          ports:
            - containerPort: 9200
              name: es-9200
              protocol: TCP
            - containerPort: 9300
              name: es-9300
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: skyworking
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "es-cluster-0.elasticsearch-service,es-cluster-1.elasticsearch-service,es-cluster-2.elasticsearch-service"
            - name: cluster.initial_master_nodes
              value: "es-cluster-0,es-cluster-1,es-cluster-2"
            - name: ES_JAVA_OPTS
              value: "-Xms4096m -Xmx4096m"
      initContainers:
        - name: init-es
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "new-nfs-storage"
        resources:
          requests:
            storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: elk-new
  labels:
    app: kibana
spec:
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk-new
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.11.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200
            - name: i18n.locale
              value: "zh-CN" 
          ports:
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: elastichd-service
  namespace: elk-new
  labels:
    app: elastichd
spec:
  type: ClusterIP
  ports:
    - port: 9800
      targetPort: 9800
      protocol: TCP
  selector:
    app: elastichd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  elastichd
  namespace: elk-new
  labels:
    app: elastichd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastichd
  template:
    metadata:
      labels:
        app:  elastichd
    spec:
      containers:
        - name: elastichd
          image: 192.168.0.40/base/elastichd:1.4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9800
