# 最少需要4个节点才能进行使用minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 4
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "root123"
        - name: MINIO_SECRET_KEY
          value: "adminadmin"
        command:
        - /bin/sh
        - -c
        - |
          /usr/bin/minio server /data
        image: minio/minio:RELEASE.2020-10-28T08-16-50Z-38-g7482aa978
        args:
        - server
        - http://minio-{0...3}.minio.default.svc.cluster.local/data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: miniodata
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: miniodata
      annotations:
        volume.beta.kubernetes.io/storage-class: nfs-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32501
      protocol: TCP
  selector:
    app: minio
