apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: public-service
spec:
  selector: 
    matchLabels:
      app: consul
  serviceName: consul
  replicas: 3s
  template: 
    metadata:
      labels:
        app: consul
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: consul-acl-config
      containers:
      - name: consul
        image: consul:1.9.7
        volumeMounts:
         - name: config
           mountPath: /consul/config
         - name: data
           mountPath: /consul/data
# 单节点   就把bootstrap-expect=3  改为 bootstrap-expect=1
# -retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local \ 去掉两个
        command: 
        - "/bin/sh"
        - "-ec"
        - |
          exec /bin/consul agent \
           -server \
           -ui \
           -advertise="$(PODIP)" \
           -bind=0.0.0.0 \
           -client=0.0.0.0 \
           -bootstrap-expect=1 \
           -data-dir=/consul/data \
           -domain=cluster.local \
           -retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local \
           -disable-host-node-id \
           -datacenter=hrfax \
           -config-file=/consul/config/Acl.json
        env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: nfs-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi