kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data
  namespace: logging
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
