apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-zjt-sa
  namespace: zhangjt
  labels:
    cluster: jenkins-zjt-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-zjt-role
  labels:
    cluster: jenkins-zjt-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "update", "list", "delete", "watch", "get", "patch", "deletecollection"]
- apiGroups: [""]
  resources: ["configmaps", "namespaces", "services", "pods"]
  verbs: ["create", "update", "list", "delete", "watch", "get", "deletecollection", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-zjt-rolebinding
  labels:
    cluster: jenkins-zjt
subjects:
- apiGroup: "" 
  kind: ServiceAccount
  name: jenkins-zjt-sa
  namespace: zhangjt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-zjt-role
