kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"  # nfs-storage  是storage-class的名字 跟上边保持一致
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
