FROM alpine:3.8

ENV SKYWALKING_VERSION=8.7.0

# https://archive.apache.org/dist/skywalking/8.7.0/apache-skywalking-apm-8.7.0.tar.gz
RUN wget http://mirrors.tuna.tsinghua.edu.cn/apache/skywalking/${SKYWALKING_VERSION}/apache-skywalking-apm-${SKYWALKING_VERSION}.tar.gz

RUN tar -zxvf apache-skywalking-apm-${SKYWALKING_VERSION}.tar.gz && \
    rm -rf apache-skywalking-apm-${SKYWALKING_VERSION}.tar.gz && \
    mkdir -p /skywalking && \
    mv apache-skywalking-apm-bin/agent /skywalking && \
    rm -rf apache-skywalking-apm-bin && \
    mv /skywalking/agent/optional-plugins/apm-trace-ignore-plugin* /skywalking/agent/plugins/ && \
    echo -e "\n# Ignore Path" >> /skywalking/agent/config/agent.config && \
    echo "# see https://github.com/apache/skywalking/blob/v8.7.0/docs/en/setup/service-agent/java-agent/agent-optional-plugins/trace-ignore-plugin.md" >> /skywalking/agent/config/agent.config && \
    echo 'trace.ignore_path=${SW_IGNORE_PATH:/health}' >> /skywalking/agent/config/agent.config
