apiVersion: v1
data:
  http-lau.yml: |
    - targets:
      - http://192.168.0.77:30091/api/actuator/health
kind: ConfigMap
metadata:
  name: http-lau
  namespace: lau
---
apiVersion: v1
data:
  ping-lau.yml: |
    - targets: ['192.168.0.159']
      labels:
        instance: '192.168.0.159'
        group: 'ping'
kind: ConfigMap
metadata:
  name: ping-lau
  namespace: lau
---
apiVersion: v1
data:
  port-lau.yml: |
    - targets: ['192.168.0.159:20010']
      labels:
        instance: 'first-java'
        group: 'tcp'
kind: ConfigMap
metadata:
  name: port-lau
  namespace: lau
