apiVersion: v1
data:
  jvm_monitor.yml: |
    - targets: ['192.168.0.77:30091']
      labels:
        instance: 'first-java-jvm'
    - targets: ['moon-jvm-svc.carloan:29999']
      labels:
        instance: 'moon-activiti-jvm-svc'
        application: 'moon-activiti-service'
    - targets: ['web-backend-jvm-svc.carloan:29999']
      labels:
        instance: 'web-backend-jvm-svc-jvm-svc'
        application: 'web-backend-servcie'
kind: ConfigMap
metadata:
  name: jvm-monitor
  namespace: zhangjt
