apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  labels:
    app: kafka
  namespace: nbbp 
spec:
  ports:
  - name: kafka-client
    nodePort: 30094
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    app: kafka
  type: NodePort
